syntax = "proto2";

package apollo.common;

enum VehicleModelType {
  VEHICLE_MODEL_TYPE_ACKERMANN_KINEMATIC = 0;
  VEHICLE_MODEL_TYPE_FOUR_WHEEL_STEERING_KINEMATIC = 1;
}

message VehicleModelConfig {
  optional VehicleModelType model_type = 1;
  optional AckermannKinematicModelConfig ackermann_kinematic_model = 2;
  optional FourWheelSteeringKinematicModelConfig fws_kinematic_model = 5;
}

message AckermannKinematicModelConfig {
  // Numerical integration step in seconds.
  optional double dt = 1;
}

message FourWheelSteeringKinematicModelConfig {
  // Numerical integration step in seconds.
  optional double dt = 1;
}
