load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "status",
    hdrs = ["status.h"],
    deps = [
        "//modules/common/util:util_tool",
        "@com_google_protobuf//:protobuf",
        "@wheelos_msgs//wheelos_msgs/basic_msgs:error_code_cc_proto",
    ],
    alwayslink = True,
)

cc_test(
    name = "status_test",
    size = "small",
    srcs = ["status_test.cc"],
    deps = [
        ":status",
        "@com_google_googletest//:gtest_main",
    ],
)
